name: Ubuntu
on: 
  push:

env: 
   code: ${{ github.event.inputs.auth }}

defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Evpn Chckr
      run: |
        git clone https://github.com/philipperemy/expressvpn-python evpn && cd evpn
        sudo dpkg -i expressvpn_2.3.4-1_amd64.deb
        pip3 install expressvpn-python
        sudo apt-get install expect -y
        expressvpn --help
    - name: initializ
      run: |   
           expect -c '
           spawn expressvpn activate
           expect "Enter activation code: "
           send "${{ secrets.code }}\r"
           expect eof
           '
